def gitUrl = "https://github.com/smart-think-app/golang-service"
pipeline {
  agent any
  stages {
    stage("git pull code") {
      steps {
        dir('golang-service'){
          echo "git pull code ${gitUrl}"
          git url: "${gitUrl}", branch: "master"
        }
      }
    }
    stage("build docker") {
      steps{
        echo "build docker"
        sh "cd golang-service && ls && docker build -t go-dk1 ."
      }
    }
  }
}