def gitUrl = "https://github.com/smart-think-app/golang-service"
pipeline {
  agent any
  stages {
    stage("git pull code") {
      steps {
        dir('golang-service/src'){
          echo "git pull code ${gitUrl}"
        }
      }
    }
    stage("run unit test") {
      steps {
        echo "run unit test"
      }
    }
    stage("build docker") {
      steps{
        echo "build docker"
      }
    }
    stage("deploy") {
      steps{
        echo "deploy"
      }
    }
  }
}